"""Agent-readable docs surface (llms.txt / llms-full.txt).

Both files are generated by ops/gen_llms_txt.py and committed at the
repo root. These tests pin:

* both files exist and regenerate byte-identically (currency guard —
  a README or docs/guide edit without a regen fails here, the same
  discipline as the docs-currency pins in test_release_ux.py);
* every docs/guide page is indexed (adding a guide page without adding
  it to the curated PAGES list fails, so the index cannot silently
  lag the docs tree).
"""
from __future__ import annotations

import importlib.util
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent

_spec = importlib.util.spec_from_file_location(
    "gen_llms_txt", REPO / "ops" / "gen_llms_txt.py",
)
gen = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(gen)


def test_llms_txt_is_committed_and_current() -> None:
    committed = (REPO / "llms.txt").read_text(encoding="utf-8")
    assert committed == gen.build_llms_txt(), (
        "llms.txt is stale — run python ops/gen_llms_txt.py"
    )


def test_llms_full_txt_is_committed_and_current() -> None:
    committed = (REPO / "llms-full.txt").read_text(encoding="utf-8")
    assert committed == gen.build_llms_full(), (
        "llms-full.txt is stale — run python ops/gen_llms_txt.py"
    )


def test_every_guide_page_is_indexed() -> None:
    indexed = {path for path, _desc in gen.PAGES}
    on_disk = {
        f"docs/guide/{p.name}" for p in (REPO / "docs" / "guide").glob("*.md")
    }
    missing = on_disk - indexed
    assert not missing, (
        f"guide pages missing from ops/gen_llms_txt.py PAGES: {sorted(missing)}"
    )


def test_llms_txt_shape() -> None:
    text = (REPO / "llms.txt").read_text(encoding="utf-8")
    assert text.startswith("# Pseudolife-MCP\n")
    assert text.count("](https://raw.githubusercontent.com/") >= len(gen.PAGES)
