"""Generate graph-name lowercase data from the Python 3.11 Unicode14 oracle.

Lowercase is a graph identity contract, including final-sigma context. The
single-character predicates below probe Python's actual lowercase behavior;
they do not substitute casefold or the host Rust compiler's Unicode version.
"""
import argparse
import hashlib
from pathlib import Path
import unicodedata

TARGET = Path(__file__).resolve().parents[1] / "src" / "storage" / "graph_unicode14.rs"


def ranges(values):
    result = []
    for value in values:
        if result and result[-1][1] + 1 == value:
            result[-1] = (result[-1][0], value)
        else:
            result.append((value, value))
    return result


def generated():
    if unicodedata.unidata_version != "14.0.0":
        raise RuntimeError("graph identity oracle requires Python Unicode 14.0.0")
    mappings, cased, ignorable = [], [], []
    digest = hashlib.sha256()
    context_digest = hashlib.sha256()
    for code in range(0x110000):
        if 0xD800 <= code <= 0xDFFF:
            continue
        char = chr(code)
        lowered = char.lower()
        digest.update(code.to_bytes(4, "little"))
        digest.update(lowered.encode("utf-8"))
        digest.update(b"\0")
        context_digest.update(code.to_bytes(4, "little"))
        for value in ("AΣ" + char + "A", "1" + char + "Σ"):
            context_digest.update(value.lower().encode("utf-8"))
            context_digest.update(b"\0")
        if lowered != char:
            mappings.append((code, lowered))
        is_cased = char.islower() or char.isupper() or char.istitle()
        if is_cased:
            cased.append(code)
        # In final-sigma context, case-ignorable characters are skipped
        # BEFORE testing whether a neighbor is cased. These two probes
        # distinguish that property even when both predicates hold.
        is_ignorable = (("1" + char + "Σ").lower()[-1] == "σ" if is_cased
                        else ("AΣ" + char + "A").lower()[1] == "σ")
        if is_ignorable:
            ignorable.append(code)
    lines = ["//! Generated by harness/gen_graph_unicode.py with Python Unicode 14.0.0.",
             "//! Graph entity identity uses lowercase, not casefold.", "",
             "pub const SINGLE_CHAR_SHA256: &str =",
             "    \"" + digest.hexdigest() + "\";", "",
             "pub const SIGMA_CONTEXT_SHA256: &str =",
             "    \"" + context_digest.hexdigest() + "\";", "",
             "pub const LOWER: &[(u32, &str)] = &["]
    for code, mapped in mappings:
        literal = "".join(f"\\u{{{ord(c):x}}}" for c in mapped)
        lines.append(f'    (0x{code:x}, "{literal}"),')
    lines.extend(["];", ""])
    for name, values in [("CASED", cased), ("IGNORABLE", ignorable)]:
        lines.append(f"pub const {name}: &[(u32, u32)] = &[")
        lines.extend(f"    (0x{lo:x}, 0x{hi:x})," for lo, hi in ranges(values))
        lines.extend(["];", ""])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = generated()
    if args.check:
        if TARGET.read_text(encoding="utf-8") != expected:
            raise SystemExit("graph Unicode14 data differs from the oracle")
        print("Graph Unicode14 data matches the oracle")
    else:
        TARGET.write_text(expected, encoding="utf-8", newline="\n")
        print("Generated graph Unicode14 lowercase and sigma-context data")


if __name__ == "__main__":
    main()
