"""Generate the Rust daemon's DDL and complete startup migration plan.

Literal SQL and constant loops are compiled from ``schema.py`` without
importing it. Database-dependent branches remain structured steps; the native
executor keeps transaction ownership and SQL parameter binding. Unsupported
constructs refuse generation. ``--check`` compares all generated bytes and a
hash of the entire source, with only checkout CRLF normalized to LF.

usage: python rust/daemon/harness/gen_schema_sql.py [--check]
"""
from __future__ import annotations

import sys
import ast
import hashlib
import json
import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[3]
TARGET = REPO / "rust" / "daemon" / "src" / "storage" / "schema.sql"
SOURCE = REPO / "pseudolife_memory/storage/schema.py"


def unsupported(node):
    raise ValueError(f"unsupported schema construct at line {node.lineno}: {ast.dump(node)}")


def is_docstring(node):
    return isinstance(node, ast.Expr) and isinstance(node.value, ast.Constant) \
        and isinstance(node.value.value, str)


def value(node, env):
    if isinstance(node, ast.Constant):
        return node.value
    if isinstance(node, ast.Name) and node.id in env:
        return env[node.id]
    if isinstance(node, (ast.Tuple, ast.List)):
        return [value(n, env) for n in node.elts]
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return value(node.left, env) + value(node.right, env)
    if isinstance(node, ast.JoinedStr):
        parts = []
        for n in node.values:
            if isinstance(n, ast.FormattedValue) and n.conversion == -1 and n.format_spec is None:
                parts.append(str(value(n.value, env)))
            elif isinstance(n, ast.Constant):
                parts.append(n.value)
            else:
                unsupported(n)
        return "".join(parts)
    if isinstance(node, ast.Call) and isinstance(node.func, ast.Name) \
            and node.func.id == "str" and len(node.args) == 1 and not node.keywords:
        return str(value(node.args[0], env))
    unsupported(node)


def predicate(node):
    if isinstance(node, ast.Name):
        return {"variable": node.id}
    if isinstance(node, ast.UnaryOp) and isinstance(node.op, ast.Not):
        return {"not": predicate(node.operand)}
    if isinstance(node, ast.Compare) and len(node.ops) == 1 \
            and isinstance(node.comparators[0], ast.Constant) \
            and node.comparators[0].value is None \
            and isinstance(node.ops[0], (ast.Is, ast.IsNot)):
        left = node.left
        field = False
        if isinstance(left, ast.Subscript) and isinstance(left.slice, ast.Constant) \
                and left.slice.value == 0:
            left, field = left.value, True
        if isinstance(left, ast.Call) and ast.unparse(left) == "cur.fetchone()":
            present = {"last": "value" if field else "row"}
            return present if isinstance(node.ops[0], ast.IsNot) else {"not": present}
    unsupported(node)


def statements(nodes, env, functions, top_level=False):
    steps = []
    for n in nodes:
        if isinstance(n, ast.Expr) and isinstance(n.value, ast.Constant) \
                and isinstance(n.value.value, str):
            continue
        if isinstance(n, ast.With) and len(n.items) == 2:
            if ast.unparse(n.items[0].context_expr) != "conn.transaction()" \
                    or ast.unparse(n.items[1].context_expr) != "conn.cursor()" \
                    or ast.unparse(n.items[1].optional_vars) != "cur":
                unsupported(n)
            steps.extend(statements(n.body, env, functions))
        elif isinstance(n, ast.For) and not n.orelse:
            for item in value(n.iter, env):
                nested = env.copy()
                if isinstance(n.target, ast.Name):
                    nested[n.target.id] = item
                elif isinstance(n.target, ast.Tuple) and len(n.target.elts) == len(item) \
                        and all(isinstance(t, ast.Name) for t in n.target.elts):
                    nested.update(zip((t.id for t in n.target.elts), item))
                else:
                    unsupported(n)
                steps.extend(statements(n.body, nested, functions))
        elif isinstance(n, ast.If):
            steps.append({"op": "if", "test": predicate(n.test),
                          "then": statements(n.body, env.copy(), functions),
                          "else": statements(n.orelse, env.copy(), functions)})
        elif isinstance(n, ast.Assign) and len(n.targets) == 1 \
                and isinstance(n.targets[0], ast.Name):
            steps.append({"op": "remember", "name": n.targets[0].id,
                          "test": predicate(n.value)})
        elif isinstance(n, ast.Expr) and isinstance(n.value, ast.Call):
            call = n.value
            if ast.unparse(call.func) == "cur.execute" and 1 <= len(call.args) <= 2 \
                    and not call.keywords:
                if ast.unparse(call) == "cur.execute(SCHEMA_SQL)":
                    steps.append({"op": "base_schema"})
                    continue
                sql = value(call.args[0], env)
                params = value(call.args[1], env) if len(call.args) == 2 else []
                if not isinstance(sql, str) or not all(isinstance(p, str) for p in params):
                    unsupported(n)
                if params:
                    if sql.count("%s") != len(params):
                        unsupported(n)
                    for i in range(len(params)):
                        sql = sql.replace("%s", f"${i + 1}", 1)
                steps.append({"op": "sql", "sql": sql, "parameters": params})
            elif ast.unparse(call) == "_refuse_on_embedding_dim_mismatch(cur)":
                steps.append({"op": "embedding_guard"})
            elif ast.unparse(call) == "_backfill_trace_invalidations(cur)":
                helper = functions["_backfill_trace_invalidations"]
                body = helper.body
                if len(body) != 3 or not is_docstring(body[0]) or not isinstance(body[1], ast.Assign) \
                        or len(body[1].targets) != 1 or not isinstance(body[1].targets[0], ast.Name) \
                        or ast.unparse(body[1].targets[0]) != "result" \
                        or ast.unparse(body[2]) != "return max(result.rowcount, 0)":
                    unsupported(helper)
                execute = body[1].value
                if not isinstance(execute, ast.Call) or ast.unparse(execute.func) != "executor.execute" \
                        or len(execute.args) != 1 or execute.keywords:
                    unsupported(helper)
                steps.append({"op": "sql", "sql": value(execute.args[0], env), "parameters": []})
            else:
                unsupported(n)
        elif isinstance(n, ast.Return) and isinstance(n.value, ast.Dict) and not n.value.keys:
            if not top_level or n is not nodes[-1]:
                unsupported(n)
        else:
            unsupported(n)
    return steps


def render(source: bytes) -> dict[str, bytes]:
    tree = ast.parse(source)
    env = {}
    for n in tree.body:
        if isinstance(n, ast.Assign) and (len(n.targets) != 1 or not isinstance(n.targets[0], ast.Name)):
            unsupported(n)
        if isinstance(n, ast.Assign) and len(n.targets) == 1 \
                and isinstance(n.targets[0], ast.Name) \
                and (n.targets[0].id.endswith("SCHEMA_SQL") or n.targets[0].id in
                     {"SCHEMA_META_VERSION", "_EXPECTED_EMBEDDING_DIM"}):
            env[n.targets[0].id] = value(n.value, env)
        elif isinstance(n, ast.AugAssign) and isinstance(n.target, ast.Name) \
                and n.target.id == "SCHEMA_SQL" and isinstance(n.op, ast.Add):
            env["SCHEMA_SQL"] += value(n.value, env)
    functions = {n.name: n for n in tree.body if isinstance(n, ast.FunctionDef)}
    guard = functions["_refuse_on_embedding_dim_mismatch"]
    body = guard.body
    if len(body) != 6 or not is_docstring(body[0]) or not isinstance(body[1], ast.Expr) \
            or ast.unparse(body[2]) != "row = cur.fetchone()" \
            or ast.unparse(body[3]) != "if row is None:\n    return" \
            or ast.unparse(body[4]) != "live_dim = row[0]" \
            or not isinstance(body[5], ast.If) \
            or ast.unparse(body[5].test) != "live_dim > 0 and live_dim != _EXPECTED_EMBEDDING_DIM" \
            or body[5].orelse or len(body[5].body) != 1 \
            or not isinstance(body[5].body[0], ast.Raise):
        unsupported(guard)
    error = body[5].body[0].exc
    if not isinstance(error, ast.Call) or ast.unparse(error.func) != "RuntimeError" \
            or len(error.args) != 1 or error.keywords or body[5].body[0].cause:
        unsupported(guard)
    probe = body[1].value
    if not isinstance(probe, ast.Call) or ast.unparse(probe.func) != "cur.execute" \
            or len(probe.args) != 1 or probe.keywords:
        unsupported(guard)
    guard_env = dict(env, live_dim="{live_dim}")
    plan = {"format": 1, "source_sha256": hashlib.sha256(source.replace(b"\r\n", b"\n")).hexdigest(),
            "schema_version": env["SCHEMA_META_VERSION"],
            "embedding_dimension": env["_EXPECTED_EMBEDDING_DIM"],
            "embedding_probe": value(probe.args[0], env),
            "embedding_refusal": value(error.args[0], guard_env),
            "steps": statements(functions["ensure_schema"].body, env, functions, top_level=True)}
    metadata = ("// Generated by harness/gen_schema_sql.py; do not edit.\n"
                f"pub const SCHEMA_META_VERSION: i64 = {plan['schema_version']};\n"
                f"pub const EXPECTED_EMBEDDING_DIM: i32 = {plan['embedding_dimension']};\n")
    return {"schema.sql": (f"-- schema_version {plan['schema_version']}\n" + env["SCHEMA_SQL"]).encode(),
            "schema_plan.json": (json.dumps(plan, indent=2, ensure_ascii=False) + "\n").encode(),
            "schema_meta.rs": metadata.encode()}


def main() -> int:
    generated = render(SOURCE.read_bytes())
    if "--check" in sys.argv:
        stale = [name for name, want in generated.items()
                 if not (TARGET.parent / name).exists() or (TARGET.parent / name).read_bytes() != want]
        if stale:
            print("stale generated schema: " + ", ".join(stale) +
                  "; rerun python rust/daemon/harness/gen_schema_sql.py", file=sys.stderr)
            return 1
        print("schema DDL and migration plan match the full Python source")
        return 0
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    for name, content in generated.items():
        (TARGET.parent / name).write_bytes(content)
    print("generated " + ", ".join(generated))
    if "--record-goldens" in sys.argv:
        output = Path(sys.argv[sys.argv.index("--record-goldens") + 1])
        return subprocess.run([sys.executable, str(Path(__file__).with_name("schema_ci.py")),
                               "--record-goldens", "--out", str(output)], cwd=REPO).returncode
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
